from types import SimpleNamespace

from onboardflow.adapters.catalogs.json_catalog import JsonCatalogAdapter
from onboardflow.adapters.crewai.orchestrator import LiveCrewAIOnboardingFlow
from onboardflow.config.settings import Settings
from onboardflow.domain.models import (
    CommunicationDraft,
    EmployeeOnboardingInput,
    ItemStatus,
    OnboardingRun,
    OnboardingPlanResult,
    ResultItem,
    SpecialistOutput,
    ValidationResult,
)


class FakeProcess:
    sequential = "sequential"


class FakeLLM:
    def __init__(self, **kwargs):
        self.kwargs = kwargs


class FakeAgent:
    def __init__(self, **kwargs):
        self.kwargs = kwargs


class FakeTask:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.config = kwargs["config"]
        self.output = None


class FakeCrew:
    def __init__(self, **kwargs):
        self.tasks = kwargs["tasks"]

    def kickoff(self, inputs):
        if "current_plan_json" in inputs:
            current_plan = OnboardingPlanResult.model_validate_json(inputs["current_plan_json"])
            data = current_plan.model_dump(mode="json", by_alias=True)
            data["executiveSummary"] = "Refined summary from fake CrewAI."
            data["status"] = "draft"
            task = self.tasks[0]
            task.output = SimpleNamespace(
                pydantic=OnboardingPlanResult.model_validate(data),
                json_dict=None,
                raw="",
            )
            return

        assert "employee_json" in inputs
        for task in self.tasks:
            task_id = task.config["description"].split("Task id: ", 1)[1].split(".", 1)[0]
            task.output = SimpleNamespace(
                pydantic=_specialist_output(task_id),
                json_dict=None,
                raw="",
            )


def _specialist_output(task_id: str) -> SpecialistOutput:
    agent_names = {
        "validate_employee_input": "HR Intake",
        "generate_document_checklist": "Compliance",
        "generate_it_checklist": "IT Provisioning",
        "generate_training_path": "Training",
        "draft_stakeholder_messages": "Communication",
    }
    items = []
    communications = []
    if task_id == "generate_document_checklist":
        items = [
            ResultItem(
                title="Crew document",
                ownerRole="RH",
                status=ItemStatus.PENDING,
                rationale="Generated by fake CrewAI task.",
            )
        ]
    if task_id == "draft_stakeholder_messages":
        communications = [
            CommunicationDraft(
                audience="hr",
                subject="Crew subject",
                body="Crew body pending human review.",
            )
        ]
    return SpecialistOutput(
        taskId=task_id,
        agentName=agent_names[task_id],
        status="done",
        summary=f"{task_id} completed",
        items=items,
        communications=communications,
        inputSources=["employee_input", "local_catalogs", "crewai"],
        qualityChecks=["json_schema_valid", "human_review_required"],
    )


def test_live_crewai_flow_executes_crew_and_normalizes_plan(monkeypatch, employee_payload):
    employee = EmployeeOnboardingInput.model_validate(employee_payload)
    flow = LiveCrewAIOnboardingFlow(
        JsonCatalogAdapter(),
        Settings(onboarding_flow_mode="crewai"),
    )
    monkeypatch.setattr(
        flow,
        "_import_crewai",
        lambda: {
            "Agent": FakeAgent,
            "Crew": FakeCrew,
            "LLM": FakeLLM,
            "Process": FakeProcess,
            "Task": FakeTask,
        },
    )

    outputs, plan = flow.execute(
        OnboardingRun(),
        employee,
        ValidationResult(status="complete"),
    )

    assert len(outputs) == 5
    assert outputs[0].input_sources == ["employee_input", "local_catalogs", "crewai"]
    assert plan.required_documents[0].title == "Documento de identificacao"
    assert "generate_document_checklist completed" not in plan.executive_summary
    assert "Resumo executivo mantido em pt-BR" in plan.executive_summary
    assert all(item.title != "Crew document" for item in plan.it_checklist)
    assert plan.communications[0].subject == "Crew subject"
    assert plan.status == "ready_for_review"


def test_live_crewai_flow_refines_plan_with_structured_output(monkeypatch, employee_payload):
    employee = EmployeeOnboardingInput.model_validate(employee_payload)
    flow = LiveCrewAIOnboardingFlow(
        JsonCatalogAdapter(),
        Settings(onboarding_flow_mode="crewai"),
    )
    monkeypatch.setattr(
        flow,
        "_import_crewai",
        lambda: {
            "Agent": FakeAgent,
            "Crew": FakeCrew,
            "LLM": FakeLLM,
            "Process": FakeProcess,
            "Task": FakeTask,
        },
    )
    _, current_plan = flow._deterministic.execute(
        OnboardingRun(),
        employee,
        ValidationResult(status="complete"),
    )

    output, refined = flow.refine(
        OnboardingRun(),
        current_plan,
        "Revisar prazos da agenda inicial.",
    )

    assert output.status == "done"
    assert output.task_id == "refine_plan_revision"
    assert "Refined summary from fake CrewAI" not in refined.executive_summary
    assert "Ajustes solicitados pelo RH foram incorporados" in refined.executive_summary
    assert refined.status == "draft"
    assert any(item.title == "Ajuste solicitado pelo RH" for item in refined.pending_actions)
